site_name: Objective 的文档站
site_url: https://objective-abk.pages.dev/docs/
copyright: Copyright © 2024-2025 <a href = "https://github.com/Federico-Prask">Federico Prask</a>, Luogu <a href = "https://www.luogu.com.cn/user/734491">Objective</a>


repo_name: 'Xiao-Han-OvO/Objective'
repo_url: 'https://github.com/Federico-Prask'

theme:
  language: 'zh'
  name: material
  # logo: box-fill
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: white
      toggle:
        icon: material/toggle-switch
        name: 切换至深色模式

    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至浅色模式
  features :
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
  icon:
    repo: fontawesome/brands/github
    logo: 'material/school'
  font:
    code: 'JetBrains Mono'
  favicon: 'favicon.ico'

extra:
  pagetime: 'on'
  disqus: 'The Doc Site of Objective'
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a>'
  alternate:
    - name: 中文（简体）
      link: /
      lang: zh
    # - name: English
    #   link: /docs/en/
    #   lang: en
  social:
    - icon: fontawesome/brands/github
      link : https://github.com/Xiao-Han-OvO/Objective
    # - icon: fontawesome/brands/wechat
    #   link : 
    # - icon: fontawesome/brands/QQ
    #   link : 

plugins:
  # - mkdocs-material-extensions
  - search
  - tags

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.progressbar
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify

nav:
  - 主页:
    - 主页: index.md
  - 题解:
    - 题解: 题解/index.md
    - 洛谷:
      - 题解：B4279 [蓝桥杯青少年组国赛 2023] 数独填数: 题解/洛谷/题解：B4279 [蓝桥杯青少年组国赛 2023] 数独填数.md
      - 题解：P12218 [蓝桥杯 2023 国 Java B] 玩具: 题解/洛谷/题解：P12218 [蓝桥杯 2023 国 Java B] 玩具.md
      - 题解：P12280 [蓝桥杯 2024 国 Python A] 特别的数组: 题解/洛谷/题解：P12280 [蓝桥杯 2024 国 Python A] 特别的数组.md
      - 题解：P12289 [蓝桥杯 2024 国 Java A] 修改数位: 题解/洛谷/题解：P12289 [蓝桥杯 2024 国 Java A] 修改数位.md
      - 题解：P12315 [蓝桥杯 2024 国 C] 挑苹果: 题解/洛谷/题解：P12315 [蓝桥杯 2024 国 C] 挑苹果.md
      - 题解：P12327 [蓝桥杯 2023 省 Java B] 蜗牛: 题解/洛谷/题解：P12327 [蓝桥杯 2023 省 Java B] 蜗牛.md
      - 题解：P12413 「YLLOI-R1-T2」圣诞星: 题解/洛谷/题解：P12413 「YLLOI-R1-T2」圣诞星.md
      - 题解：P13134 [GCJ 2018 Qualification] Go, Gopher!: 题解/洛谷/题解：P13134 [GCJ 2018 Qualification] Go, Gopher!.md
      - 题解：P13422 [COCI 2019&2020 4] Pod starim krovovima: 题解/洛谷/题解：P13422 [COCI 2019&2020 4] Pod starim krovovima.md
  - 游记:
    - 游记: 游记/index.md
    - 2025 暑 TYOI 集训小记: 游记/2025 暑 TYOI 集训小记.md

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css